//============================================================================
// Module : spi_master.v
// Project: Space-Grade Vibration Pattern Anomaly Detector (GF180, 180nm)
//----------------------------------------------------------------------------
// Function:
//   SPI master that reads 16-bit two's-complement PCM samples from an external
//   space-grade ADC (e.g. AD7980 class converter), MSB-first.
//
// GF180 Power Strategy:
//   The FSM rests in an IDLE state with SCLK held STATIC (no toggling) and
//   CS_N de-asserted high. A free-running sample-rate timer (SAMPLE_DIV) is
//   the ONLY logic that switches while idle. A conversion burst is launched
//   only when the timer expires, which keeps dynamic switching power minimal.
//
// Notes:
//   * Synchronous, active-low reset (rst_n).
//   * SCLK is generated by dividing clk by 2*SCLK_DIV (50% duty).
//   * data_ready is a single-clk-wide pulse asserted when x_n is valid.
//============================================================================
`timescale 1ns/1ps
`default_nettype none

module spi_master #(
    parameter integer SAMPLE_W = 16,   // ADC word width (bits)
    parameter integer SCLK_DIV = 4,    // clk cycles per SCLK half-period
    parameter integer SAMPLE_DIV = 1000 // clk cycles between sample acquisitions
)(
    input  wire                     clk,
    input  wire                     rst_n,
    input  wire                     miso,        // serial data in from ADC

    output reg                      sclk,        // serial clock to ADC
    output reg                      cs_n,        // active-low chip select
    output reg                      data_ready,  // 1-cycle pulse, x_n valid
    output reg  signed [SAMPLE_W-1:0] x_n        // captured signed sample
);

    //------------------------------------------------------------------------
    // Local parameters / counter widths
    //------------------------------------------------------------------------
    localparam integer BITCNT_W  = $clog2(SAMPLE_W) + 1;
    localparam integer SCLKCNT_W = $clog2(SCLK_DIV) + 1;
    localparam integer SMPCNT_W  = $clog2(SAMPLE_DIV) + 1;

    // FSM states (one-hot avoided to save flops; binary is smaller on GF180)
    localparam [1:0] ST_IDLE    = 2'd0,  // resting, sclk static
                     ST_START   = 2'd1,  // assert cs_n low, settle
                     ST_SHIFT   = 2'd2,  // toggle sclk, shift in 16 bits
                     ST_DONE    = 2'd3;  // present sample + data_ready pulse

    reg [1:0]            state;
    reg [SMPCNT_W-1:0]   sample_timer;  // sample-rate timer
    reg [SCLKCNT_W-1:0]  sclk_cnt;      // SCLK half-period counter
    reg [BITCNT_W-1:0]   bit_cnt;       // bits shifted so far
    reg [SAMPLE_W-1:0]   shift_reg;     // MSB-first receive shifter

    wire sample_tick = (sample_timer == SAMPLE_DIV[SMPCNT_W-1:0] - 1'b1);
    wire sclk_tick   = (sclk_cnt     == SCLK_DIV[SCLKCNT_W-1:0]   - 1'b1);

    //------------------------------------------------------------------------
    // Free-running sample-rate timer (only active block during IDLE)
    //------------------------------------------------------------------------
    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            sample_timer <= {SMPCNT_W{1'b0}};
        end else if (state == ST_IDLE) begin
            if (sample_tick)
                sample_timer <= {SMPCNT_W{1'b0}};
            else
                sample_timer <= sample_timer + 1'b1;
        end else begin
            // Hold timer reset while a conversion is in progress
            sample_timer <= {SMPCNT_W{1'b0}};
        end
    end

    //------------------------------------------------------------------------
    // Main acquisition FSM
    //------------------------------------------------------------------------
    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            state      <= ST_IDLE;
            sclk       <= 1'b0;       // SCLK parked low while idle (no toggle)
            cs_n       <= 1'b1;       // ADC de-selected
            data_ready <= 1'b0;
            x_n        <= {SAMPLE_W{1'b0}};
            sclk_cnt   <= {SCLKCNT_W{1'b0}};
            bit_cnt    <= {BITCNT_W{1'b0}};
            shift_reg  <= {SAMPLE_W{1'b0}};
        end else begin
            // data_ready is strictly a 1-cycle pulse; default low every cycle
            data_ready <= 1'b0;

            case (state)
                //------------------------------------------------------------
                // IDLE: SCLK static, CS_N high. Wait for sample-rate tick.
                //------------------------------------------------------------
                ST_IDLE: begin
                    sclk     <= 1'b0;
                    cs_n     <= 1'b1;
                    sclk_cnt <= {SCLKCNT_W{1'b0}};
                    bit_cnt  <= {BITCNT_W{1'b0}};
                    if (sample_tick) begin
                        cs_n  <= 1'b0;          // select ADC, begin conversion read
                        state <= ST_START;
                    end
                end

                //------------------------------------------------------------
                // START: one settle period with CS_N low before clocking.
                //------------------------------------------------------------
                ST_START: begin
                    cs_n <= 1'b0;
                    if (sclk_tick) begin
                        sclk_cnt <= {SCLKCNT_W{1'b0}};
                        state    <= ST_SHIFT;
                    end else begin
                        sclk_cnt <= sclk_cnt + 1'b1;
                    end
                end

                //------------------------------------------------------------
                // SHIFT: generate SCLK, sample MISO on rising edge, MSB-first.
                //------------------------------------------------------------
                ST_SHIFT: begin
                    if (sclk_tick) begin
                        sclk_cnt <= {SCLKCNT_W{1'b0}};
                        sclk     <= ~sclk;
                        if (~sclk) begin
                            // Rising edge of SCLK -> capture one MISO bit (MSB first)
                            shift_reg <= {shift_reg[SAMPLE_W-2:0], miso};
                            bit_cnt   <= bit_cnt + 1'b1;
                            if (bit_cnt == SAMPLE_W[BITCNT_W-1:0] - 1'b1) begin
                                state <= ST_DONE;
                            end
                        end
                    end else begin
                        sclk_cnt <= sclk_cnt + 1'b1;
                    end
                end

                //------------------------------------------------------------
                // DONE: park SCLK, raise CS_N, present sample, pulse ready.
                //------------------------------------------------------------
                ST_DONE: begin
                    sclk       <= 1'b0;
                    cs_n       <= 1'b1;
                    x_n        <= shift_reg;     // signed two's-complement sample
                    data_ready <= 1'b1;          // 1-cycle valid pulse
                    state      <= ST_IDLE;
                end

                default: state <= ST_IDLE;
            endcase
        end
    end

endmodule

`default_nettype wire
