PDK: gf180mcuD
DESIGN_NAME: top
VERILOG_FILES:
  - dir::../../rtl/*.v


LINTER_DISABLE_WARNINGS_BLACKBOX: ["UNDRIVEN", "UNUSEDSIGNAL", "TIMESCALEMOD", "PINMISSING"]

LINTER_DISABLE_WARNINGS: ["DECLFILENAME", "EOFNEWLINE", "MODDUP", "MODMISSING", "PINCONNECTEMPTY", "WIDTHEXPAND", "UNUSEDPARAM", "UNUSEDSIGNAL", "CASEINCOMPLETE", "SYNCASYNCNET"]