// Auto-generated by LibreLane
module top(
`ifdef USE_POWER_PINS
  inout VDD,
  inout VSS,
`endif
  input clk,
  input sys_rst_n,
  input c_miso,
  output c_csn,
  output c_sclk,
  output c_mosi,
  input sensor_drdy,
  input tmr_forward_en,
  input cmd_sclk,
  input cmd_csn,
  input cmd_mosi,
  output fault_flag_out
);
endmodule
